### ISSUE TITLE
Standalone vs master/worker mode

### ISSUE THREAD

**Issue by sebastian-kucharzyk-tcl** [aws-samples/distributed-load-testing-with-locust-on-ecs#16]
Hello,

I am currently reviewing the Dockerfile in this repository and need some clarification regarding the commented-out code sections related to configuring Locust in different modes.

Specifically, I am trying to understand the implications of uncommenting the various lines for standalone, worker, and master modes. The current comments indicate that Locust is set up for standalone mode, but I am unclear about the exact meaning and implications of this setup.

Could you please provide more details on:

1. What the standalone mode entails in the context of this Dockerfile? Does it imply that only the master component is operational?
2. If uncommenting the worker or master sections is necessary, how would these changes affect the behavior of Locust? Would it mean that both master and worker operate as separate, unconnected instances?
3. In case I need to configure a distributed setup with both master and worker roles, what steps should I follow to ensure proper connectivity and coordination between these components?

I have included the relevant section of the Dockerfile for reference:

```
FROM --platform=linux/amd64 locustio/locust:2.8.3
COPY . ./

# for standalone
ENTRYPOINT ["locust", "-f", "./locustfile.py"]
# for worker
# CMD [ "--worker", "--master-host", "MASTER_HOST_NAME"]
# for master
# CMD ["--master"]
```

Any insights or guidance you can provide on this matter would be greatly appreciated.

Thank you for your time and assistance.

**Comment by tmokmss** [comment]
Hi @sebastian-kucharzyk-tcl, the CMD field is overridden here when deploying to AWS:

* worker
https://github.com/aws-samples/distributed-load-testing-with-locust-on-ecs/blob/4b66fea19a1daffab5c573e90c23ae220a0a098c/lib/constructs/locust_worker_service.ts#L29

* master
https://github.com/aws-samples/distributed-load-testing-with-locust-on-ecs/blob/4b66fea19a1daffab5c573e90c23ae220a0a098c/lib/constructs/locust_master_service.ts#L45-L53

By default it runs in standalone mode (I use it for local test purpose only.)

You can read more details about Locust distributed mode [here](https://docs.locust.io/en/stable/running-distributed.html).
